[package]
name = "depot-smart-boat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
itertools = "0.11.0"
picovoice = "3.0.1"
rppal = { version = "0.15.0", optional = true }

[features]
on_target = ["dep:rppal"]
